import type { GameEvent } from "./types";

export const EVENTS: GameEvent[] = [
  {
    id: "greve-generale",
    cond: (s) => s.cohesion < 45,
    text: "Une grève générale intersyndicale paralyse les transports pendant une semaine.",
    fx: { croissance: -0.2, popularite: -5, deficit: 0.1 },
  },
  {
    id: "emeutes",
    cond: (s) => s.securite < 45,
    text: "Des émeutes urbaines éclatent dans plusieurs grandes villes après un fait divers.",
    fx: { securite: -8, popularite: -6, cohesion: -4 },
  },
  {
    id: "degradation-note",
    cond: (s) => s.dette > 118,
    text: "Une agence de notation dégrade la note de la dette française. Les taux d'emprunt s'envolent.",
    fx: { deficit: 0.4, dette: 2, popularite: -4 },
  },
  {
    id: "motion-censure",
    cond: (s) => s.popularite < 35,
    text: "Une motion de censure est déposée à l'Assemblée. Elle échoue de justesse.",
    fx: { popularite: -3, cohesion: -3 },
  },
  {
    id: "ralentissement",
    cond: (s) => s.croissance < 0.5,
    text: "L'INSEE confirme un ralentissement marqué de la croissance ce trimestre.",
    fx: { chomage: 0.3, deficit: 0.2, popularite: -3 },
  },
  {
    id: "sommet-europe",
    cond: (s) => s.rayonnement < 40,
    text: "La France est marginalisée lors d'un sommet européen clé sur la défense.",
    fx: { rayonnement: -4, popularite: -2 },
  },
  {
    id: "scandale-ministre",
    cond: () => true,
    text: "Un scandale politique mineur éclabousse un ministre du gouvernement. La presse s'en empare.",
    fx: { popularite: -4 },
  },
  {
    id: "choc-energie",
    cond: () => true,
    text: "Une tension commerciale internationale fait bondir le prix de l'énergie.",
    fx: { croissance: -0.2, popularite: -3, cohesion: -2 },
  },
  {
    id: "sondage-embellie",
    cond: (s) => s.popularite > 60,
    text: "Un sondage confirme une embellie de l'opinion. La majorité reprend confiance.",
    fx: { popularite: 3, cohesion: 2 },
  },
  {
    id: "commerce-exterieur",
    cond: (s) => s.croissance > 1.3,
    text: "De bons chiffres du commerce extérieur redonnent de l'optimisme aux marchés.",
    fx: { croissance: 0.1, rayonnement: 2, popularite: 2 },
  },
  {
    id: "bruxelles-salue",
    cond: (s) => s.deficit < 4,
    text: "Bruxelles salue les efforts budgétaires engagés par la France.",
    fx: { rayonnement: 3, popularite: 2 },
  },
  {
    id: "canicule",
    cond: () => true,
    text: "Une canicule sévère pèse sur le système de santé et l'agriculture.",
    fx: { croissance: -0.1, cohesion: -2 },
  },
  {
    id: "fait-divers",
    cond: () => true,
    text: "Un fait divers judiciaire relance le débat sur la sécurité dans l'opinion.",
    fx: { securite: -2, popularite: -1 },
  },
  {
    id: "climat-apaise",
    cond: (s) => s.cohesion > 60,
    text: "Le climat social apaisé permet de faire passer une réforme sans heurts majeurs.",
    fx: { deficit: -0.1, popularite: 2 },
  },
  {
    id: "greve-enseignants",
    cond: (s) => s.cohesion < 50,
    text: "Une grève des enseignants gèle des milliers d'établissements pendant plusieurs jours.",
    fx: { cohesion: -3, popularite: -2 },
  },
  {
    id: "crise-hopital",
    cond: () => true,
    text: "Les urgences saturées forcent plusieurs CHU à déclencher le plan blanc.",
    fx: { cohesion: -3, popularite: -2, deficit: 0.1 },
  },
  {
    id: "colere-agricole",
    cond: () => true,
    text: "Des blocages agricoles paralysent des axes routiers et des marchés de gros.",
    fx: { croissance: -0.1, cohesion: -3, popularite: -2 },
  },
  {
    id: "cyberattaque",
    cond: () => true,
    text: "Une cyberattaque vise des services publics critiques. L'État doit contenir la panique.",
    fx: { securite: -3, rayonnement: -2, popularite: -2 },
  },
  {
    id: "inondations",
    cond: () => true,
    text: "Des inondations majeures touchent plusieurs départements. Les sinistrés demandent des aides d'urgence.",
    fx: { deficit: 0.2, cohesion: -2, popularite: -1 },
  },
  {
    id: "attentat-foile",
    cond: (s) => s.securite < 55,
    text: "Un attentat à la voiture-bélier fait plusieurs victimes. L'émotion nationale est vive.",
    fx: { securite: -5, popularite: -3, cohesion: -2 },
  },
  {
    id: "fuite-presse",
    cond: () => true,
    text: "Une fuite dans la presse révèle des arbitrages budgétaires internes à Matignon.",
    fx: { popularite: -3, cohesion: -1 },
  },
  {
    id: "sommet-g7",
    cond: (s) => s.rayonnement >= 55,
    text: "Au G7, la France obtient un rôle de médiateur sur un dossier stratégique.",
    fx: { rayonnement: 4, popularite: 2 },
  },
  {
    id: "investissement-etranger",
    cond: (s) => s.croissance >= 1.1 && s.deficit <= 4.5,
    text: "Un grand groupe annonce un investissement industriel majeur en France.",
    fx: { chomage: -0.2, croissance: 0.1, popularite: 2 },
  },
  {
    id: "chomage-baisse",
    cond: (s) => s.chomage <= 6.8,
    text: "L'INSEE publie une baisse inattendue du chômage. Les marchés applaudissent.",
    fx: { popularite: 3, cohesion: 2, croissance: 0.1 },
  },
  {
    id: "hausse-taux",
    cond: (s) => s.dette > 115,
    text: "La BCE laisse entendre une période prolongée de taux élevés. La charge de la dette s'alourdit.",
    fx: { deficit: 0.3, dette: 1, popularite: -2 },
  },
  {
    id: "crise-logement",
    cond: (s) => s.cohesion < 55,
    text: "La crise du logement devient le premier sujet des Français dans les sondages.",
    fx: { cohesion: -3, popularite: -3 },
  },
  {
    id: "victoire-diplomatique",
    cond: (s) => s.rayonnement > 58,
    text: "Une médiation française aboutit à un cessez-le-feu régional. Paris gagne en stature.",
    fx: { rayonnement: 5, popularite: 3 },
  },
  {
    id: "manifestation-retraites",
    cond: (s) => s.popularite < 45,
    text: "Des manifestations massives contre la réforme des retraites remplissent les avenues.",
    fx: { cohesion: -4, popularite: -3, securite: -1 },
  },
  {
    id: "embellie-tourisme",
    cond: (s) => s.securite >= 55 && s.rayonnement >= 48,
    text: "Une saison touristique record gonfle les recettes et l'image du pays.",
    fx: { croissance: 0.15, popularite: 2, rayonnement: 1 },
  },
  {
    id: "procedure-bruxelles",
    cond: (s) => s.deficit > 5,
    text: "Bruxelles ouvre une procédure renforcée pour déficit excessif. L'Élysée est sous pression.",
    fx: { rayonnement: -3, popularite: -3, deficit: 0.1 },
  },
];
