import type { Current, Impacts, Measure, Pillar } from "./types";

type Row = [string, Pillar, string, string, string, Impacts];

function pack(current: Current, rows: Row[]): Measure[] {
  return rows.map(([id, pillar, cat, title, desc, fx]) => ({
    id,
    current,
    pillar,
    cat,
    title,
    desc,
    fx,
  }));
}

export const MEASURES: Measure[] = [
  ...pack("extreme-gauche", [
    [
      "xg-retraite-60",
      "social",
      "Retraites",
      "Retraite à 60 ans pour toutes et tous",
      "Promesse-phare de rupture. Les caisses craquent, la rue applaudit, les marchés reculent.",
      { deficit: 0.8, dette: 2, cohesion: 9, popularite: 10, croissance: -0.25, rayonnement: -4 },
    ],
    [
      "xg-retraite-salaires",
      "social",
      "Retraites",
      "Indexation des pensions sur les salaires",
      "Les retraités suivent la hausse des salaires. Juste, populaire, et très cher dès que l'inflation revient.",
      { deficit: 0.35, cohesion: 6, popularite: 7, croissance: -0.05 },
    ],
    [
      "xg-retraite-smic",
      "social",
      "Retraites",
      "Pension minimale alignée sur le SMIC net",
      "Plus de retraites sous le seuil de pauvreté. Bercy sort le chéquier, les cotisants aussi.",
      { deficit: 0.45, cohesion: 7, popularite: 8, chomage: 0.1 },
    ],
    [
      "xg-tva-zero",
      "economie",
      "TVA",
      "TVA à 0 % sur l'alimentation et l'énergie",
      "Le levier le plus visible du pouvoir d'achat. Un trou immédiat dans la TVA, premier impôt de l'État.",
      { deficit: 0.7, popularite: 11, cohesion: 6, croissance: 0.1, rayonnement: -2 },
    ],
    [
      "xg-tva-luxe",
      "economie",
      "TVA",
      "TVA à 33 % sur le luxe, yachts et jets privés",
      "Symbole fort, recette limitée. Une partie de l'assiette s'évapore vers Monaco ou Dublin.",
      { deficit: -0.1, popularite: 6, cohesion: 4, croissance: -0.1, rayonnement: -2 },
    ],
    [
      "xg-isf",
      "economie",
      "Fiscalité",
      "Rétablissement d'un ISF élargi aux hauts patrimoines",
      "Recettes et popularité à gauche. Risque d'exil fiscal et de bras de fer avec le CAC 40.",
      { deficit: -0.25, popularite: 8, cohesion: 5, croissance: -0.2, rayonnement: -3 },
    ],
    [
      "xg-smic-1600",
      "social",
      "Pouvoir d'achat",
      "SMIC à 1 600 € net",
      "Coup de pouce massif aux bas salaires. Les TPE licencient, la conso tient un trimestre.",
      { popularite: 9, cohesion: 7, chomage: 0.5, croissance: -0.2, deficit: 0.15 },
    ],
    [
      "xg-blocage-prix",
      "economie",
      "Pouvoir d'achat",
      "Blocage des prix alimentaires pendant 18 mois",
      "Soulage les caddies tout de suite. Les rayons se vident, l'investissement agro recule.",
      { popularite: 8, cohesion: 5, croissance: -0.25, chomage: 0.15 },
    ],
    [
      "xg-32h",
      "social",
      "Travail",
      "Semaine de 32 heures sans perte de salaire",
      "Partage du temps de travail. Coût pour les entreprises, espoir pour l'emploi — pas garanti.",
      { cohesion: 6, popularite: 5, croissance: -0.3, chomage: 0.2, deficit: 0.1 },
    ],
    [
      "xg-nationalisations",
      "economie",
      "Industrie",
      "Renationalisation d'EDF et des autoroutes",
      "Souveraineté et tarifs administrés. Facture d'emprunt, contentieux, et signal aux investisseurs.",
      { deficit: 0.4, dette: 3, cohesion: 5, popularite: 6, croissance: -0.15, rayonnement: -3 },
    ],
    [
      "xg-gel-loyers",
      "social",
      "Logement",
      "Gel national des loyers",
      "Les locataires respirent. Les bailleurs reportent les travaux, l'offre se contracte.",
      { cohesion: 7, popularite: 7, croissance: -0.2 },
    ],
    [
      "xg-regularisation",
      "securite",
      "Immigration",
      "Régularisation des travailleurs sans-papiers",
      "Sortir de l'angle mort. Une partie de l'opinion hurle, une autre parle de dignité.",
      { cohesion: 3, popularite: -6, securite: -3, rayonnement: 3, croissance: 0.1 },
    ],
    [
      "xg-traites-ue",
      "international",
      "Europe",
      "Suspension des traités budgétaires européens",
      "Marge de manœuvre immédiate. Bruxelles, Berlin et les agences de notation s'étranglent.",
      { deficit: 0.3, popularite: 4, rayonnement: -8, dette: 2 },
    ],
    [
      "xg-budget-militaire",
      "international",
      "Défense",
      "Gel du budget militaire au profit de la diplomatie",
      "Moins d'économie de guerre, plus de conférences. L'OTAN et l'industrie d'armement grincent.",
      { deficit: -0.15, rayonnement: -6, securite: -4, cohesion: 3 },
    ],
    [
      "xg-embauches-public",
      "social",
      "Services publics",
      "500 000 embauches dans la fonction publique",
      "Hôpital, école, préfectures. Le service public reprend de la chair — et la masse salariale aussi.",
      { deficit: 0.55, cohesion: 8, popularite: 7, chomage: -0.3, croissance: 0.1 },
    ],
    [
      "xg-planification",
      "international",
      "Écologie",
      "Planification écologique par filières",
      "L'État oriente l'investissement vert. Lent, coûteux, lisible pour une partie de la jeunesse.",
      { deficit: 0.35, croissance: 0.2, cohesion: 4, popularite: 3, rayonnement: 3 },
    ],
    [
      "xg-abrogation-immigration",
      "securite",
      "Immigration",
      "Abrogation des lois immigration restrictives",
      "Retour à une politique d'accueil. Mobilise les associations, polarise le pays.",
      { cohesion: -4, popularite: -5, securite: -4, rayonnement: 4 },
    ],
    [
      "xg-requisition",
      "social",
      "Logement",
      "Réquisition des logements vacants",
      "Toits contre spéculation. Contentieux, maires récalcitrants, et un symbole qui marque.",
      { cohesion: 6, popularite: 5, croissance: -0.1 },
    ],
    [
      "xg-cantines",
      "social",
      "École",
      "Gratuité des cantines et des transports scolaires",
      "Pouvoir d'achat des familles, coût pour les collectivités déjà étranglées.",
      { deficit: 0.2, cohesion: 6, popularite: 6 },
    ],
    [
      "xg-medicament",
      "social",
      "Santé",
      "Pôle public du médicament essentiel",
      "Souveraineté sanitaire. Investissement lourd, résultats dans cinq ans, pas dans six mois.",
      { deficit: 0.25, cohesion: 4, popularite: 3, rayonnement: 2 },
    ],
  ]),
  ...pack("gauche", [
    [
      "g-retraite-62",
      "social",
      "Retraites",
      "Retour de la retraite à 62 ans",
      "Abroger 64 ans sans aller jusqu'à 60. Coûteux, populaire à gauche, encore trop pour Bercy.",
      { deficit: 0.45, cohesion: 6, popularite: 7, dette: 1, rayonnement: -2 },
    ],
    [
      "g-penibilite",
      "social",
      "Retraites",
      "Départ anticipé pour les carrières pénibles",
      "BTP, nuit, aidants : on reconnaît l'usure. Complexe à piloter, juste politiquement.",
      { deficit: 0.2, cohesion: 5, popularite: 4 },
    ],
    [
      "g-minimum-contributif",
      "social",
      "Retraites",
      "Minimum contributif revalorisé de 10 %",
      "Les petites pensions remontent. Moins spectaculaire que 60 ans, plus finançable.",
      { deficit: 0.2, cohesion: 5, popularite: 5 },
    ],
    [
      "g-tva-energie",
      "economie",
      "TVA",
      "TVA à 5,5 % sur l'électricité et le gaz",
      "Factures allégées, recette TVA en berne. Un classique de campagne — et de lettre à Bruxelles.",
      { deficit: 0.3, popularite: 7, cohesion: 4 },
    ],
    [
      "g-tva-alimentaire",
      "economie",
      "TVA",
      "TVA à 2,1 % sur l'alimentation de base",
      "Le caddie comme levier. Moins radical que le taux zéro, déjà un trou de plusieurs milliards.",
      { deficit: 0.25, popularite: 6, cohesion: 4, croissance: 0.05 },
    ],
    [
      "g-superprofits",
      "economie",
      "Fiscalité",
      "Taxe pérenne sur les superprofits",
      "Énergie, banques, luxe : on pique le surplus. Recette réelle, investissement plus prudent.",
      { deficit: -0.25, popularite: 6, cohesion: 3, croissance: -0.1 },
    ],
    [
      "g-smic-10",
      "social",
      "Pouvoir d'achat",
      "Coup de pouce de 10 % au SMIC",
      "Soutien franc aux bas salaires, sans le choc du 1 600 €. L'emploi des peu qualifiés trinque un peu.",
      { popularite: 7, cohesion: 5, chomage: 0.2, croissance: -0.1 },
    ],
    [
      "g-hopital",
      "social",
      "Santé",
      "Plan d'urgence pour l'hôpital public",
      "Lits, soignants, gardes. Les Français applaudissent, le déficit aussi.",
      { deficit: 0.3, cohesion: 7, popularite: 6, chomage: -0.1 },
    ],
    [
      "g-ecole",
      "social",
      "École",
      "Dédoublement des classes et revalorisation des enseignants",
      "L'école comme promesse républicaine. Coûteux, lent, et très lisible pour les parents.",
      { deficit: 0.3, cohesion: 6, popularite: 5 },
    ],
    [
      "g-loyers",
      "social",
      "Logement",
      "Encadrement des loyers étendu à 50 métropoles",
      "Soulage les locataires urbains. Les bailleurs crient, l'offre neuve hésite.",
      { cohesion: 5, popularite: 5, croissance: -0.1 },
    ],
    [
      "g-pass-rail",
      "economie",
      "Pouvoir d'achat",
      "Pass rail à 49 € par mois",
      "Le train comme service public du quotidien. Subvention massive, popularité immédiate.",
      { deficit: 0.2, popularite: 6, cohesion: 4, croissance: 0.05 },
    ],
    [
      "g-rsa",
      "social",
      "Pouvoir d'achat",
      "Revalorisation du RSA de 10 %",
      "Filet plus haut pour les plus précaires. Débat féroce sur « l'assistanat ».",
      { deficit: 0.15, cohesion: 5, popularite: 2 },
    ],
    [
      "g-creches",
      "social",
      "Famille",
      "200 000 places en crèches publiques",
      "Emploi des femmes, natalité, service public. La facture s'étale sur le quinquennat.",
      { deficit: 0.2, cohesion: 5, popularite: 4, croissance: 0.1, chomage: -0.1 },
    ],
    [
      "g-conditionnalite",
      "economie",
      "Industrie",
      "Aides aux entreprises conditionnées à l'emploi et au climat",
      "Plus de chèque en blanc au CAC 40. Certaines filières temporisent leurs investissements.",
      { deficit: -0.1, cohesion: 3, popularite: 3, croissance: -0.1 },
    ],
    [
      "g-europe-sociale",
      "international",
      "Europe",
      "Salaire minimum européen et clause sociale",
      "La gauche veut une Europe qui protège. Négociation longue, rayonnement si ça avance.",
      { rayonnement: 4, cohesion: 3, popularite: 2, croissance: -0.05 },
    ],
    [
      "g-climat",
      "international",
      "Écologie",
      "Plan climat à 100 milliards sur cinq ans",
      "Rénovation, ferroviaire, industrie verte. La croissance future se paie aujourd'hui.",
      { deficit: 0.4, croissance: 0.25, rayonnement: 5, cohesion: 4, popularite: 3 },
    ],
    [
      "g-regularisation-cas",
      "securite",
      "Immigration",
      "Régularisation au cas par cas des métiers en tension",
      "Ni ouverture totale, ni fermeture. Un équilibre que personne n'aime vraiment.",
      { popularite: -2, cohesion: 1, securite: -1, croissance: 0.1, rayonnement: 2 },
    ],
    [
      "g-deserts",
      "social",
      "Santé",
      "Plan pour les déserts médicaux",
      "Médecins salariés, maisons de santé. Attente forte, effets lents.",
      { deficit: 0.2, popularite: 5, cohesion: 5 },
    ],
    [
      "g-conference",
      "social",
      "Travail",
      "Grande conférence sociale avec les syndicats",
      "On parle avant de décréter. Apaise le climat, ne règle pas Bercy.",
      { cohesion: 6, popularite: 2 },
    ],
    [
      "g-cheque-energie",
      "social",
      "Pouvoir d'achat",
      "Chèque énergie renforcé pour les ménages modestes",
      "Ciblé, lisible, moins cher qu'une TVA zéro — et moins universel.",
      { deficit: 0.12, popularite: 4, cohesion: 3 },
    ],
  ]),
  ...pack("centre", [
    [
      "c-retraite-64",
      "social",
      "Retraites",
      "Maintien de la retraite à 64 ans",
      "Ne pas reculer, ne pas avancer. Les caisses respirent, une partie du pays ne décolère pas.",
      { deficit: -0.15, cohesion: -5, popularite: -4, rayonnement: 2, dette: -1 },
    ],
    [
      "c-penibilite-ciblee",
      "social",
      "Retraites",
      "Compte pénibilité recentré sur les métiers usants",
      "Un filet pour le BTP et le soin, pas une usine à contentieux. Technique, un peu sourd.",
      { deficit: 0.08, cohesion: 2, popularite: 1 },
    ],
    [
      "c-emploi-seniors",
      "economie",
      "Retraites",
      "Bonus-malus pour l'emploi des 60-64 ans",
      "Travailler plus longtemps n'a de sens que s'il y a du travail. Les entreprises râlent du malus.",
      { chomage: -0.15, croissance: 0.1, cohesion: -2, popularite: 1, deficit: -0.05 },
    ],
    [
      "c-tva-sociale",
      "economie",
      "TVA",
      "TVA sociale : +1 point, baisse des charges",
      "On finance la protection sociale par la conso plutôt que par le travail. Technique, explosif.",
      { deficit: -0.2, croissance: 0.15, chomage: -0.15, popularite: -5, cohesion: -3 },
    ],
    [
      "c-tva-energie",
      "economie",
      "TVA",
      "TVA à 5,5 % sur l'énergie, limitée à deux hivers",
      "Un geste de pouvoir d'achat borné dans le temps. Bruxelles tolère, Bercy compte les mois.",
      { deficit: 0.2, popularite: 5, cohesion: 3 },
    ],
    [
      "c-baisse-is",
      "economie",
      "Fiscalité",
      "Baisse ciblée de l'impôt sur les sociétés",
      "Pari sur l'attractivité. Creuse le déficit avant de (peut-être) ramener l'investissement.",
      { deficit: 0.2, croissance: 0.3, rayonnement: 3, popularite: -1 },
    ],
    [
      "c-simplification",
      "economie",
      "Administration",
      "Plan de simplification administrative",
      "Moins de normes, plus vite. Gains modestes, bien perçus par les entreprises.",
      { deficit: -0.08, croissance: 0.2, popularite: 3 },
    ],
    [
      "c-plan-ia",
      "economie",
      "Industrie",
      "Grand plan d'investissement dans l'IA et l'industrie",
      "Coûteux à court terme, pari sur la croissance et l'attractivité.",
      { deficit: 0.3, croissance: 0.55, rayonnement: 6, popularite: 3 },
    ],
    [
      "c-assurance-chomage",
      "social",
      "Travail",
      "Assurance chômage un peu plus stricte",
      "Inciter au retour à l'emploi sans casser le filet. Les syndicats dénoncent, Pôle emploi applaudit.",
      { deficit: -0.12, chomage: -0.2, cohesion: -4, popularite: -3 },
    ],
    [
      "c-snu",
      "securite",
      "Cohésion",
      "Service national universel généralisé",
      "Un rite républicain pour la jeunesse. Coût d'organisation, consentement inégal.",
      { deficit: 0.12, securite: 3, cohesion: 1, popularite: 1, rayonnement: 2 },
    ],
    [
      "c-cyber",
      "securite",
      "Sécurité",
      "Renforcement de la cybersécurité de l'État",
      "Investissement discret, stratégique, peu visible pour l'opinion.",
      { deficit: 0.1, securite: 4, rayonnement: 3 },
    ],
    [
      "c-niches",
      "economie",
      "Fiscalité",
      "Rabot sur les niches fiscales inefficaces",
      "On ferme des tuyaux. Recettes, grogne sectorielle, et un signal de sérieux.",
      { deficit: -0.25, croissance: -0.1, popularite: 1 },
    ],
    [
      "c-immigration-choisie",
      "securite",
      "Immigration",
      "Immigration choisie : quotas par métier",
      "Ni naïveté, ni fermeture. Un tableau Excel qui ne passionne personne et mécontente les deux ailes.",
      { securite: 2, popularite: 1, cohesion: -2, croissance: 0.1, rayonnement: 1 },
    ],
    [
      "c-deserts",
      "social",
      "Santé",
      "Incitations fiscales pour les médecins en zone rurale",
      "Moins spectaculaire que l'hôpital public, plus cheap. Les déserts attendent encore.",
      { deficit: 0.08, cohesion: 3, popularite: 2 },
    ],
    [
      "c-france-2030",
      "international",
      "Industrie",
      "France 2030 bis : technologies vertes et nucléaire",
      "Investissement d'État dans la transition, sans planification autoritaire.",
      { deficit: 0.28, croissance: 0.3, rayonnement: 5, cohesion: 2 },
    ],
    [
      "c-couple-fa",
      "international",
      "Europe",
      "Relance du couple franco-allemand",
      "Un sommet à l'Élysée pour débloquer industrie et défense. Classique, parfois efficace.",
      { rayonnement: 6, croissance: 0.15, popularite: 2 },
    ],
    [
      "c-europe-defense",
      "international",
      "Défense",
      "Initiative pour l'Europe de la défense",
      "Paris veut peser sans attendre Washington. Résultats incertains, image de sérieux.",
      { rayonnement: 6, popularite: 1, deficit: 0.1 },
    ],
    [
      "c-prime-activite",
      "social",
      "Pouvoir d'achat",
      "Prime d'activité renforcée",
      "Soutenir ceux qui travaillent, sans toucher au SMIC. Ciblé, un peu technocrate.",
      { deficit: 0.12, popularite: 3, cohesion: 2, chomage: -0.05 },
    ],
    [
      "c-regle-or",
      "economie",
      "Budget",
      "Règle d'or : déficit structurel plafonné",
      "On se lie les mains pour rassurer. Moins de marges pour la prochaine crise.",
      { deficit: -0.3, rayonnement: 4, popularite: -3, cohesion: -2, dette: -1 },
    ],
    [
      "c-csg",
      "economie",
      "Fiscalité",
      "Hausse de la CSG de 0,3 point",
      "Recette large, visible sur la fiche de paie. Moins brutale que 0,5, déjà impopulaire.",
      { deficit: -0.25, popularite: -4, cohesion: -2 },
    ],
  ]),
  ...pack("droite", [
    [
      "retraite-65",
      "economie",
      "Retraites",
      "Report de l'âge de la retraite à 65 ans",
      "Économie budgétaire majeure, très impopulaire, risque de mobilisation sociale.",
      { deficit: -0.6, cohesion: -10, popularite: -8, dette: -1 },
    ],
    [
      "d-regimes-speciaux",
      "economie",
      "Retraites",
      "Alignement des derniers régimes spéciaux",
      "L'équité par le haut de la cotisation. Cheminots et électriciens dans la rue.",
      { deficit: -0.2, cohesion: -6, popularite: -4 },
    ],
    [
      "d-decote",
      "economie",
      "Retraites",
      "Décote renforcée en cas de départ anticipé",
      "On ne touche pas l'âge légal, on pèse sur ceux qui partent tôt. Technique, dur.",
      { deficit: -0.15, cohesion: -4, popularite: -3 },
    ],
    [
      "d-tva-21",
      "economie",
      "TVA",
      "TVA à 21 % : un point de plus pour Bercy",
      "L'impôt le plus indolore pour l'État, le plus visible pour les caddies. Recette massive.",
      { deficit: -0.45, popularite: -7, cohesion: -4, croissance: -0.1, dette: -1 },
    ],
    [
      "d-tva-recentrage",
      "economie",
      "TVA",
      "Recentrage des taux réduits de TVA",
      "On garde 5,5 % sur le pain, plus sur le reste. Moins de cadeaux sectoriels, plus de TVA.",
      { deficit: -0.2, popularite: -3, cohesion: -2 },
    ],
    [
      "d-collectivites",
      "economie",
      "Budget",
      "Baisse ciblée des concours aux collectivités",
      "Économies significatives. Les maires parlent de services de proximité en danger.",
      { deficit: -0.35, cohesion: -4, popularite: -2 },
    ],
    [
      "d-carence",
      "economie",
      "Budget",
      "Jour de carence supplémentaire dans la fonction publique",
      "Petites économies récurrentes, tension avec les syndicats de fonctionnaires.",
      { deficit: -0.15, cohesion: -4, popularite: -3 },
    ],
    [
      "d-gel-indice",
      "economie",
      "Budget",
      "Gel du point d'indice des fonctionnaires",
      "Économie immédiate. Fonctionnaires mécontents, risque de grève dans les services publics.",
      { deficit: -0.25, cohesion: -5, popularite: -4 },
    ],
    [
      "d-police",
      "securite",
      "Sécurité",
      "Recrutement de 8 000 policiers et gendarmes",
      "Coûteux mais très demandé. L'autorité de l'État reprend de la voix.",
      { deficit: 0.22, securite: 9, popularite: 6 },
    ],
    [
      "d-justice-mineurs",
      "securite",
      "Justice",
      "Justice des mineurs plus rapide et plus ferme",
      "Mesure clivante. Plaît à une partie de l'opinion, inquiète les magistrats.",
      { securite: 5, cohesion: -4, popularite: 3 },
    ],
    [
      "d-migration",
      "securite",
      "Immigration",
      "Durcissement des titres de séjour et des OQTF",
      "Forte demande sociale, tensions diplomatiques et associatives.",
      { securite: 5, popularite: 4, rayonnement: -3, cohesion: -3 },
    ],
    [
      "d-narcotrafic",
      "securite",
      "Sécurité",
      "Plan anti-narcotrafic dans les métropoles",
      "Résultats à moyen terme, coût opérationnel, popularité d'ordre public.",
      { deficit: 0.15, securite: 7, popularite: 4 },
    ],
    [
      "d-heures-sup",
      "economie",
      "Travail",
      "Heures supplémentaires défiscalisées",
      "Travailler plus pour gagner plus, version 2027. Coûte à l'impôt, plaît aux salariés en poste.",
      { deficit: 0.15, popularite: 4, croissance: 0.15, cohesion: 1 },
    ],
    [
      "d-rsa-travail",
      "social",
      "Travail",
      "RSA contre 15 heures d'activité",
      "La contrepartie comme dogme. Une partie du pays applaudit, les associations dénoncent.",
      { deficit: -0.1, chomage: -0.1, cohesion: -5, popularite: 2 },
    ],
    [
      "d-rearmement",
      "international",
      "Défense",
      "Plan de réarmement et souveraineté industrielle",
      "La France pèse, Bercy paie. Fierté nationale, déficit en hausse.",
      { deficit: 0.3, rayonnement: 7, securite: 4, popularite: 3 },
    ],
    [
      "d-nucleaire",
      "economie",
      "Énergie",
      "Accélération du programme nucléaire",
      "Souveraineté électrique à 15 ans. Emplois, dette, et un signal aux industriels.",
      { deficit: 0.25, croissance: 0.2, rayonnement: 4, cohesion: 1 },
    ],
    [
      "d-loyers-libres",
      "economie",
      "Logement",
      "Fin de l'encadrement des loyers",
      "L'offre d'abord. Les locataires urbains trinquent, les investisseurs reviennent.",
      { croissance: 0.15, cohesion: -5, popularite: -4 },
    ],
    [
      "d-3-pourcent",
      "economie",
      "Budget",
      "Trajectoire vers les 3 % de déficit",
      "Le sérieux selon Bruxelles. Coupes, gel, et un pays qui trouve le temps long.",
      { deficit: -0.5, rayonnement: 5, popularite: -6, cohesion: -4, dette: -2, croissance: -0.15 },
    ],
    [
      "d-non-remplacement",
      "economie",
      "Administration",
      "Non-remplacement d'un fonctionnaire sur deux partant",
      "La masse salariale recule. Les files s'allongent à la CAF et à l'hôpital.",
      { deficit: -0.3, cohesion: -6, popularite: -4, chomage: 0.1 },
    ],
    [
      "d-apprentissage",
      "economie",
      "Travail",
      "Choc d'apprentissage et bascule vers l'alternance",
      "Moins d'université par défaut, plus d'entreprises formatrices. Ça marche — lentement.",
      { chomage: -0.25, croissance: 0.15, popularite: 2, deficit: 0.08 },
    ],
  ]),
  ...pack("extreme-droite", [
    [
      "xd-retraite-60-nationaux",
      "social",
      "Retraites",
      "Retraite à 60 ans pour les carrières longues, nationaux d'abord",
      "On baisse l'âge — mais pas pour tout le monde. Populaire dans l'électorat, juridiquement explosif.",
      { deficit: 0.4, popularite: 6, cohesion: -6, rayonnement: -5 },
    ],
    [
      "xd-pensions-preference",
      "social",
      "Retraites",
      "Préférence nationale sur les minima vieillesse",
      "Les solidarités d'abord pour « les nôtres ». Contentieux européens, fracture du pays.",
      { deficit: -0.1, popularite: 5, cohesion: -8, rayonnement: -6 },
    ],
    [
      "xd-tva-carburant",
      "economie",
      "TVA",
      "TVA à 0 % sur les carburants et l'énergie",
      "Le pouvoir d'achat des ronds-points. Un gouffre pour l'État, un camouflet climatique.",
      { deficit: 0.75, popularite: 10, cohesion: 3, croissance: 0.1, rayonnement: -4 },
    ],
    [
      "xd-tva-alimentaire",
      "economie",
      "TVA",
      "TVA à 5,5 % sur toute l'alimentation",
      "Le caddie comme argument de campagne. Moins radical que le taux zéro, déjà très cher.",
      { deficit: 0.3, popularite: 6, cohesion: 3 },
    ],
    [
      "xd-schengen",
      "securite",
      "Immigration",
      "Rétablissement des frontières et sortie de Schengen",
      "Le contrôle d'abord. Freins aux échanges, colère de Bruxelles, aplaudi au comptoir.",
      { securite: 7, popularite: 6, rayonnement: -8, croissance: -0.2, cohesion: -3 },
    ],
    [
      "xd-expulsions",
      "securite",
      "Immigration",
      "Expulsions massives des déboutés du droit d'asile",
      "La fermeté comme méthode. Capacités consulaires, avions, et une France polarisée.",
      { securite: 6, popularite: 5, cohesion: -6, rayonnement: -5, deficit: 0.1 },
    ],
    [
      "xd-ame",
      "social",
      "Santé",
      "Suppression de l'aide médicale d'État",
      "Économie réelle, risque sanitaire, et un symbole que la droite dure réclame depuis vingt ans.",
      { deficit: -0.08, popularite: 4, cohesion: -5, securite: -1, rayonnement: -3 },
    ],
    [
      "xd-droit-sol",
      "securite",
      "Immigration",
      "Abrogation du droit du sol",
      "La nationalité se mérite. Contentieux constitutionnel, jeunesse concernée, pays fendu.",
      { popularite: 4, cohesion: -7, rayonnement: -5, securite: 2 },
    ],
    [
      "xd-hlm",
      "social",
      "Logement",
      "Priorité nationale dans l'attribution des HLM",
      "Loger « les Français d'abord ». Illégal au regard du droit actuel, électoralement parlant.",
      { popularite: 5, cohesion: -7, rayonnement: -4 },
    ],
    [
      "xd-europe-nations",
      "international",
      "Europe",
      "Europe des nations : fin du fédéralisme budgétaire",
      "On reste, on désobéit. Marge de manœuvre, isolation à Bruxelles.",
      { popularite: 4, rayonnement: -7, deficit: 0.15, dette: 1 },
    ],
    [
      "xd-moratoire",
      "securite",
      "Immigration",
      "Moratoire migratoire de cinq ans",
      "On ferme le robinet. Agriculture et BTP manquent de bras, l'opinion sécuritaire applaudit.",
      { securite: 5, popularite: 5, croissance: -0.2, chomage: 0.1, cohesion: -4, rayonnement: -4 },
    ],
    [
      "xd-natalite",
      "social",
      "Famille",
      "Allocations familiales réservées aux nationaux",
      "Natalité « française » comme projet. Discrimination, contentieux, électorat fidélisé.",
      { deficit: -0.05, popularite: 3, cohesion: -6, rayonnement: -4 },
    ],
    [
      "xd-rearmement-fr",
      "international",
      "Défense",
      "Réarmement 100 % français, hors commandes étrangères",
      "Souveraineté industrielle à marche forcée. Plus cher, plus lent, plus « made in France ».",
      { deficit: 0.35, rayonnement: 3, securite: 3, croissance: 0.15, popularite: 3 },
    ],
    [
      "xd-islamisme",
      "securite",
      "Sécurité",
      "Plan contre l'islamisme politique et les frères musulmans",
      "Dissolutions, contrôles, écoles. Une partie du pays demande, une autre parle de stigmatisation.",
      { securite: 6, popularite: 4, cohesion: -6, rayonnement: -3 },
    ],
    [
      "xd-police-municipale",
      "securite",
      "Sécurité",
      "Police municipale armée obligatoire",
      "L'ordre au plus près. Coût pour les mairies, sentiment de sécurité en hausse.",
      { deficit: 0.1, securite: 5, popularite: 4, cohesion: -2 },
    ],
    [
      "xd-relocalisation",
      "economie",
      "Industrie",
      "Relocalisation forcée par droits de douane",
      "On protège l'usine française. L'inflation des importations, et l'UE attaque.",
      { croissance: 0.1, chomage: -0.15, popularite: 4, rayonnement: -6, deficit: 0.1 },
    ],
    [
      "xd-referendum",
      "securite",
      "Institutions",
      "Référendum d'initiative présidentielle sur l'immigration",
      "Rendre la parole au peuple. Polarise tout, n'équilibre rien, et peut tout bloquer.",
      { popularite: 5, cohesion: -8, rayonnement: -3 },
    ],
    [
      "xd-decheance",
      "securite",
      "Immigration",
      "Déchéance de nationalité élargie",
      "Le régalien comme théâtre. Effet réel limité, effet politique maximal.",
      { securite: 3, popularite: 4, cohesion: -5, rayonnement: -4 },
    ],
    [
      "xd-sieges",
      "economie",
      "Fiscalité",
      "Surcote fiscale pour les sièges étrangers",
      "Punir ceux qui facturent en France et paient ailleurs. Fuite de quelques QG.",
      { deficit: -0.1, popularite: 3, croissance: -0.15, rayonnement: -3 },
    ],
    [
      "xd-service-militaire",
      "securite",
      "Défense",
      "Rétablissement du service militaire obligatoire",
      "La nation sous les drapeaux. Coût énorme, jeunesse partagée, image de fermeté.",
      { deficit: 0.3, securite: 5, cohesion: -3, popularite: 3, rayonnement: 2 },
    ],
  ]),
];

export const PILLAR_META: Record<
  Measure["pillar"],
  { label: string; blurb: string; seal: string }
> = {
  economie: {
    label: "Économie & Budget",
    blurb: "Déficit, dette, fiscalité, industrie.",
    seal: "BERCY",
  },
  securite: {
    label: "Sécurité & Ordre public",
    blurb: "Police, justice, immigration, cyber.",
    seal: "PLACE BEAUVAU",
  },
  social: {
    label: "Social & Cohésion",
    blurb: "Retraites, santé, école, pouvoir d'achat.",
    seal: "MATIGNON",
  },
  international: {
    label: "International & Rayonnement",
    blurb: "Europe, défense, diplomatie, industrie.",
    seal: "QUAI D'ORSAY",
  },
};
