import type { Measure } from "./types";

export const MEASURES: Measure[] = [
  {
    id: "retraite-65",
    pillar: "economie",
    cat: "Économie",
    title: "Report de l'âge de la retraite à 65 ans",
    desc: "Économie budgétaire majeure, mais très impopulaire et risque de mobilisation sociale.",
    fx: { deficit: -0.6, cohesion: -10, popularite: -8, dette: -1 },
  },
  {
    id: "jour-carence",
    pillar: "economie",
    cat: "Économie",
    title: "Jour de carence supplémentaire fonction publique",
    desc: "Petites économies récurrentes, tension avec les syndicats de fonctionnaires.",
    fx: { deficit: -0.15, cohesion: -4, popularite: -3 },
  },
  {
    id: "niches-fiscales",
    pillar: "economie",
    cat: "Économie",
    title: "Suppression de niches fiscales aux entreprises",
    desc: "Recettes supplémentaires, grogne du patronat, risque sur l'investissement.",
    fx: { deficit: -0.3, croissance: -0.2, popularite: 2 },
  },
  {
    id: "csg-05",
    pillar: "economie",
    cat: "Économie",
    title: "Hausse de la CSG de 0,5 point",
    desc: "Recette large et rapide, mais directement visible sur les fiches de paie.",
    fx: { deficit: -0.4, popularite: -6, cohesion: -3 },
  },
  {
    id: "gel-indice",
    pillar: "economie",
    cat: "Économie",
    title: "Gel du point d'indice des fonctionnaires",
    desc: "Économie immédiate, fonctionnaires mécontents, risque de grève dans les services publics.",
    fx: { deficit: -0.25, cohesion: -5, popularite: -4 },
  },
  {
    id: "simplification",
    pillar: "economie",
    cat: "Économie",
    title: "Plan de simplification administrative",
    desc: "Gains d'efficacité modestes mais réels, bien perçu par les entreprises.",
    fx: { deficit: -0.1, croissance: 0.2, popularite: 3 },
  },
  {
    id: "collectivites",
    pillar: "economie",
    cat: "Économie",
    title: "Baisse ciblée des dépenses des collectivités locales",
    desc: "Économies significatives, tension avec les élus locaux et services de proximité.",
    fx: { deficit: -0.35, cohesion: -3 },
  },
  {
    id: "plan-ia",
    pillar: "economie",
    cat: "Économie",
    title: "Grand plan d'investissement dans l'IA et l'industrie",
    desc: "Coûteux à court terme mais pari sur la croissance et l'attractivité future.",
    fx: { deficit: 0.3, croissance: 0.6, rayonnement: 6, popularite: 4 },
  },
  {
    id: "taxe-patrimoine",
    pillar: "economie",
    cat: "Économie",
    title: "Taxe exceptionnelle sur les hauts patrimoines",
    desc: "Recettes symboliques, forte popularité populaire, risque d'exil fiscal.",
    fx: { deficit: -0.2, popularite: 7, croissance: -0.15, cohesion: 4 },
  },
  {
    id: "baisse-is",
    pillar: "economie",
    cat: "Économie",
    title: "Baisse de l'impôt sur les sociétés",
    desc: "Pari sur l'attractivité, creuse le déficit à court terme.",
    fx: { deficit: 0.25, croissance: 0.35, rayonnement: 3 },
  },
  {
    id: "tva-energie",
    pillar: "economie",
    cat: "Économie",
    title: "TVA réduite à 5,5 % sur l'énergie",
    desc: "Soulage les factures, coûte cher à Bercy, plaît immédiatement aux ménages.",
    fx: { deficit: 0.25, popularite: 6, cohesion: 3 },
  },
  {
    id: "police-5000",
    pillar: "securite",
    cat: "Sécurité",
    title: "Recrutement de 5 000 policiers et gendarmes",
    desc: "Coûteux mais très populaire, améliore le sentiment de sécurité.",
    fx: { deficit: 0.2, securite: 9, popularite: 6 },
  },
  {
    id: "justice-mineurs",
    pillar: "securite",
    cat: "Sécurité",
    title: "Réforme de la justice des mineurs",
    desc: "Mesure clivante, plaît à une partie de l'opinion, inquiète les magistrats.",
    fx: { securite: 5, cohesion: -4, popularite: 2 },
  },
  {
    id: "migration",
    pillar: "securite",
    cat: "Sécurité",
    title: "Durcissement de la politique migratoire",
    desc: "Forte demande sociale, tensions diplomatiques et associatives.",
    fx: { securite: 6, popularite: 5, rayonnement: -4, cohesion: -3 },
  },
  {
    id: "narcotrafic",
    pillar: "securite",
    cat: "Sécurité",
    title: "Plan anti-narcotrafic dans les quartiers",
    desc: "Résultats visibles à moyen terme, coût opérationnel important.",
    fx: { deficit: 0.15, securite: 7, popularite: 4 },
  },
  {
    id: "cyber",
    pillar: "securite",
    cat: "Sécurité",
    title: "Renforcement de la cybersécurité de l'État",
    desc: "Investissement discret mais stratégique, peu visible pour l'opinion.",
    fx: { deficit: 0.1, securite: 3, rayonnement: 3 },
  },
  {
    id: "snu",
    pillar: "securite",
    cat: "Sécurité",
    title: "Service national universel obligatoire",
    desc: "Fierté républicaine pour certains, contrainte pour d'autres, coût d'organisation réel.",
    fx: { deficit: 0.15, securite: 4, cohesion: -2, popularite: 1, rayonnement: 2 },
  },
  {
    id: "smic",
    pillar: "social",
    cat: "Social",
    title: "Revalorisation du SMIC au-delà de l'inflation",
    desc: "Soutien au pouvoir d'achat, coût pour les entreprises, risque sur l'emploi.",
    fx: { popularite: 7, cohesion: 5, croissance: -0.1, chomage: 0.2 },
  },
  {
    id: "deserts-medicaux",
    pillar: "social",
    cat: "Social",
    title: "Plan santé pour les déserts médicaux",
    desc: "Réponse à une attente forte, coûteux et lent à produire des effets visibles.",
    fx: { deficit: 0.2, popularite: 5, cohesion: 4 },
  },
  {
    id: "ecole",
    pillar: "social",
    cat: "Social",
    title: "Grand plan pour l'école et les enseignants",
    desc: "Revalorisation salariale et moyens supplémentaires, coût élevé.",
    fx: { deficit: 0.25, cohesion: 6, popularite: 4 },
  },
  {
    id: "assurance-chomage",
    pillar: "social",
    cat: "Social",
    title: "Réforme de l'assurance chômage (plus stricte)",
    desc: "Fait des économies, incite au retour à l'emploi, mal perçue par les précaires.",
    fx: { deficit: -0.2, chomage: -0.3, cohesion: -6, popularite: -5 },
  },
  {
    id: "cheque-energie",
    pillar: "social",
    cat: "Social",
    title: "Chèque énergie renforcé pour les ménages modestes",
    desc: "Réponse ciblée à la précarité énergétique, coût maîtrisé.",
    fx: { deficit: 0.1, popularite: 4, cohesion: 3 },
  },
  {
    id: "conference-sociale",
    pillar: "social",
    cat: "Social",
    title: "Grande conférence sociale avec les syndicats",
    desc: "Apaise le climat social sans grande mesure concrète immédiate.",
    fx: { cohesion: 6, popularite: 2 },
  },
  {
    id: "loyers",
    pillar: "social",
    cat: "Social",
    title: "Encadrement des loyers dans les métropoles",
    desc: "Soulage les locataires urbains, crispe les bailleurs, effet contrasté sur l'offre.",
    fx: { cohesion: 5, popularite: 4, croissance: -0.15 },
  },
  {
    id: "rearmement",
    pillar: "international",
    cat: "International",
    title: "Plan de réarmement et souveraineté industrielle",
    desc: "Renforce la position stratégique de la France, coûteux, source de fierté nationale.",
    fx: { deficit: 0.3, rayonnement: 8, securite: 3, popularite: 3 },
  },
  {
    id: "europe-defense",
    pillar: "international",
    cat: "International",
    title: "Initiative pour relancer l'Europe de la défense",
    desc: "Renforce le poids diplomatique français, résultats incertains à court terme.",
    fx: { rayonnement: 7, popularite: 2 },
  },
  {
    id: "afrique",
    pillar: "international",
    cat: "International",
    title: "Grand accord commercial avec l'Afrique francophone",
    desc: "Ouvre des débouchés économiques, pari de long terme.",
    fx: { croissance: 0.25, rayonnement: 5 },
  },
  {
    id: "france-2030",
    pillar: "international",
    cat: "International",
    title: "Plan France 2030 bis pour les technologies vertes",
    desc: "Investissement massif dans la transition énergétique et l'industrie verte.",
    fx: { deficit: 0.3, croissance: 0.3, rayonnement: 5, cohesion: 3 },
  },
  {
    id: "regles-ue",
    pillar: "international",
    cat: "International",
    title: "Renégociation stricte des règles budgétaires européennes",
    desc: "Gagne en marge de manœuvre budgétaire, tensions avec Bruxelles et l'Allemagne.",
    fx: { deficit: -0.2, rayonnement: -3, popularite: 3 },
  },
  {
    id: "couple-franco-allemand",
    pillar: "international",
    cat: "International",
    title: "Relance du couple franco-allemand",
    desc: "Un sommet à l'Élysée pour débloquer l'industrie et la défense européennes.",
    fx: { rayonnement: 6, croissance: 0.15, popularite: 2 },
  },
];

export const PILLAR_META: Record<
  Measure["pillar"],
  { label: string; blurb: string; seal: string }
> = {
  economie: {
    label: "Économie & Budget",
    blurb: "Déficit, dette, fiscalité, industrie.",
    seal: "BERCY",
  },
  securite: {
    label: "Sécurité & Ordre public",
    blurb: "Police, justice, immigration, cyber.",
    seal: "PLACE BEAUVAU",
  },
  social: {
    label: "Social & Cohésion",
    blurb: "Retraites, santé, école, pouvoir d'achat.",
    seal: "MATIGNON",
  },
  international: {
    label: "International & Rayonnement",
    blurb: "Europe, défense, diplomatie, industrie.",
    seal: "QUAI D'ORSAY",
  },
};
